"""CleanPlay Phase 3 — deploy + live-invoke the RocketRide Cloud pipeline.

Proves the hard requirement: the `cleanplay_score` pipeline runs on RocketRide
Cloud (api.rocketride.ai) and responds when invoked remotely. Scores a real
device from Neo4j, ships the result to the cloud pipeline, and prints the live
LLM case report it returns.

Run:  python scripts/deploy_pipeline.py [DEVICE_ID]   (default D-42)
"""
from __future__ import annotations

import asyncio
import os
import sys

from scoring import score_device_standalone
from rocketride_report import generate_case_report, PIPE


async def main() -> int:
    device_id = sys.argv[1] if len(sys.argv) > 1 else "D-42"
    print(f"RocketRide Cloud endpoint : {os.environ['ROCKETRIDE_URI']}")
    print(f"Pipeline file             : {PIPE.name}")
    print(f"Scoring device            : {device_id}\n")

    scoring = score_device_standalone(device_id)
    print(f"Local score  -> {scoring['verdict'].upper()} ({scoring['score']}/100), "
          f"accounts={scoring['affected_accounts']}")

    print("Invoking deployed pipeline on RocketRide Cloud ...")
    out = await generate_case_report(scoring)

    print(f"\nCloud task token          : {out['token']}")
    print("=" * 72)
    print("LIVE CASE REPORT (generated by Claude on RocketRide Cloud):")
    print("=" * 72)
    print(out["report_text"])
    print("=" * 72)

    ok = bool(out["report_text"])
    print("\nREMOTE INVOCATION:", "PASS ✅ (cloud pipeline responded)" if ok
          else "FAIL ❌ (empty response)")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
